Feature: serializer design pattern
TheDevJoao/TO-DO-design-patterns pull request #2
Opened 2023-03-07 18:03 UTC by TheDevJoao

Resolves [issue](https://github.com/TheDevJoao/TO-DO-design-patterns/issues/1)

- [x] creates tasks_serializer.rb class
- [x] refactors the complete method to use the serializer
- [x] created a unit test for the serializer

2023-03-08 13:38 UTC, tonyaraujop commented on spec/serializers/task_serializer_spec.rb
> +      }
You can move this to a `let` and will clean the `it` block.

2023-03-08 13:39 UTC, tonyaraujop requested changes
left some suggestion. Good job so far

2023-03-08 14:07 UTC, HeitorMC requested changes
Change the PR title `feat` for `Feature` :nail_care:

2023-03-08 14:07 UTC, HeitorMC commented on spec/serializers/task_serializer_spec.rb
> +  let(:serializer) { described_class.new(task, user) }
makes more sense if you change this `let` to:

```rb
    subject(:serializer) { described_class.new(task, user) }
```

2023-03-08 14:07 UTC, HeitorMC commented on spec/serializers/task_serializer_spec.rb
> +  let(:task) { create(:task) }
I think you can test here with `build_stubbed` because you pass a hash to the class. Try it and tell me later :smile:

2023-03-08 16:20 UTC, TheDevJoao commented on app/serializers/task_serializer.rb
> +  attr_reader :task, :user
Ah, true! Refactoring this soon!

2023-03-08 16:26 UTC, TheDevJoao commented on spec/serializers/task_serializer_spec.rb
> +      }
Will do!

2023-03-08 16:52 UTC, TheDevJoao commented on spec/serializers/task_serializer_spec.rb
> +  let(:serializer) { described_class.new(task, user) }
True! Makes more sense to test the class instance in this case.

2023-03-08 18:57 UTC, TheDevJoao commented on spec/serializers/task_serializer_spec.rb
> +  let(:task) { create(:task) }
Refactored this in my latest commit! create was not necessary.

2023-03-08 19:00 UTC, HeitorMC approved these changes
LGTM!

2023-03-09 12:11 UTC, tonyaraujop approved these changes
LGTM

2023-03-09 13:11 UTC, merged