feat: service object design pattern
TheDevJoao/TO-DO-design-patterns pull request #4
Opened 2023-03-08 15:02 UTC by TheDevJoao

Resolves [issue](https://github.com/TheDevJoao/TO-DO-design-patterns/issues/3)

- [x] creates application_service class to negate the use of states in the controller.
- [x] creates task_completer service class that inherits the application_service
- [x] refactors the complete method to use the service object
- [x] created a unit test for the task_completer service

2023-03-08 19:29 UTC, HeitorMC requested changes

2023-03-08 19:29 UTC, HeitorMC commented on app/services/task_completer.rb
> +  def call
You can improve this method. Too many `if`s statements in this method, also did you pass rubocop in this class? :eyes:

Rubocop will complain with `Method has too many lines`.

One could move these multiple cases into a hash, similar to the calculator problem. Or maybe, you could apply a factory pattern here. 

WDYT?

2023-03-08 19:29 UTC, HeitorMC commented on spec/services/task_completer_spec.rb
> +  describe '#call' do
This should be:
```rb
describe '.call'
```
Because your implementation uses a class method, not a instance method

2023-03-08 19:29 UTC, HeitorMC commented on spec/services/task_completer_spec.rb
> +    context 'when task is not completed' do
Also, I think you could implement tests for each notification preference here. And check if the function was called right after. 

WDTY? @tonyaraujop

2023-03-08 19:45 UTC, TheDevJoao commented on app/services/task_completer.rb
> +  def call
Sounds good! Yeah I executed rubocop and it reccomended reducing the amount of lines in this method, my next commit should resolve these issues.

2023-03-09 12:12 UTC, HeitorMC commented on app/services/task_completer.rb
> +  def call
Ok then, we have a deal :handshake:

2023-03-09 12:16 UTC, HeitorMC approved these changes
I'm approving this PR as long you make the changes in the next pr, as we talked :handshake:

2023-03-09 13:13 UTC, merged